// Non-secret conference details, loaded from environment so they can change
// without touching code. Keep this file free of anything sensitive.
export const siteConfig = {
  institution: "Ogun State Institute of Technology, Igbesa",
  institutionShort: "OGITECH",
  school: "School of Engineering Technology",
  conferenceTitle: "Hybrid International Conference — 2nd Edition",
  theme:
    "Repositioning Engineering TVET for Industrial Development and Global Competitiveness in Nigeria",
  dates: "2nd – 5th November, 2026",
  venue: "Prince Dapo Abiodun Twin Hall A, OGITECH, Igbesa, Ogun State",
  venueName: "Prince Dapo Abiodun Twin Hall A",
  venueLocation: "OGITECH, Igbesa, Ogun State",
  venueMapsUrl: "https://www.google.com/maps/search/?api=1&query=Ogun+State+Institute+of+Technology+Igbesa",
  // Countdown target: 2 November 2026, 00:00 West Africa Time (UTC+1)
  conferenceStartISO: "2026-11-02T00:00:00+01:00",
  conferenceEndISO: "2026-11-05T23:59:59+01:00",
  appUrl: process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000",
  contact: {
    email: process.env.CONFERENCE_EMAIL ?? "conference@ogitech.edu.ng",
    chairmanName: process.env.CHAIRMAN_NAME ?? "Engr. Ifeka O. I.",
    chairmanPhone: process.env.CHAIRMAN_PHONE ?? "0807650613",
    secretaryName: process.env.SECRETARY_NAME ?? "Engr. Adeimpe H. A.",
    secretaryPhone: process.env.SECRETARY_PHONE ?? "0703399672",
  },
  bank: {
    accountName: process.env.BANK_ACCOUNT_NAME ?? "School of Engineering Technology",
    bankName: process.env.BANK_NAME ?? "Access Bank",
    accountNumber: process.env.BANK_ACCOUNT_NUMBER ?? "0800088752",
  },
  importantDates: [
    { label: "Abstract Submission", iso: "2026-09-20", day: "20", month: "September", year: "2026", kind: "deadline" },
    { label: "Full Paper — Early-bird", iso: "2026-10-20", day: "20", month: "October", year: "2026", kind: "deadline" },
    { label: "Full Paper — Late-bird", iso: "2026-10-27", day: "27", month: "October", year: "2026", kind: "deadline" },
    { label: "Conference", iso: "2026-11-02", day: "2–5", month: "November", year: "2026", kind: "event" },
  ],
  focusAreas: [
    "Engineering TVET",
    "Industrial development",
    "Global competitiveness",
    "Technology",
    "Innovation",
    "Skills development",
    "Industry 4.0",
    "Nigeria's engineering and technical education ecosystem",
  ],
  attendees: [
    "Researchers",
    "Academics",
    "Engineers",
    "Students",
    "Industry professionals",
    "TVET stakeholders",
  ],
  objectives: [
    {
      title: "Reposition engineering TVET",
      text: "Re-examine how technical and vocational engineering education is designed, delivered and valued in Nigeria.",
    },
    {
      title: "Connect institutions and industry",
      text: "Strengthen the link between training institutions, employers and industrial practice.",
    },
    {
      title: "Advance research and innovation",
      text: "Provide a platform for researchers to present work on the conference sub-themes, with published papers available in a public library.",
    },
    {
      title: "Build globally competitive skills",
      text: "Support skills development in automation, digital technologies, manufacturing, construction and sustainable energy.",
    },
  ],
  subThemes: [
    "Advancing Embedded Systems and Robotic and IoT Skills Development for Industrial Automation in Nigeria.",
    "Cybersecurity and Network Protection Strategies for TVET Institutions.",
    "Developing Software Solutions for Digital Transformation in Nigerian TVET Institutions.",
    "Innovation in Electrical and Electronic Engineering for Sustainable Energy.",
    "Smart Technologies, and Industrial Development.",
    "Digital Transformation and Industry 4.0 in Civil TVET.",
    "Sustainable Construction and Local Material Innovation.",
    "Construction Entrepreneurship and Maintenance Engineering.",
    "Advanced Manufacturing and Smart Production Systems in TVET.",
    "Maintenance Engineering and Asset Management in Industrial Development.",
    "Materials Engineering and Sustainable Composites for Industrial Applications.",
    "Nigeria's Emerging Manufacturing Economy.",
    "Human-Machine Collaboration, Digital Twins, and Intelligent Control in Next-Generation Mechatronics.",
    "Low-Cost Mechatronic System Design, Prototyping, and Local Innovation for Industrial Resilience in Nigeria.",
    "Repositioning Welding and Fabrication Technology in Engineering TVET.",
    "Developing Competencies in Automation and Control Systems for Smart Manufacturing in Nigeria.",
  ],
  registration: {
    physical: {
      earlyBird: { participant: "₦20,000", student: "₦5,000" },
      lateBird: { participant: "₦25,000", student: "₦5,000" },
    },
    virtual: {
      earlyBird: { participant: "₦15,000", student: "₦5,000" },
      lateBird: { participant: "₦20,000", student: "₦5,000" },
    },
    international: "$50",
  },
  advertisement: {
    fullPage: "₦50,000",
    halfPage: "₦30,000",
    quarterPage: "₦20,000",
  },
  paperRequirements: {
    maxPages: "10 pages",
    spacing: "Double-space, line spacing 1.5",
    font: "12-point Times New Roman",
    referencing: "APA 7th Edition",
    presentation: "PowerPoint",
    plagiarism: "Less than 20%",
  },
  accommodation: [
    { hotel: "Topson Hotel & Suites", price: "₦10,000 – ₦15,000" },
    { hotel: "Temluc Hotel & Suites", price: "₦15,000 – ₦20,000" },
    { hotel: "Morvic Hotel & Suites", price: "₦10,000 – ₦20,000" },
    { hotel: "O Royal Hotel & Suites", price: "₦15,000 – ₦30,000" },
  ],
  navigation: [
    { label: "Home", href: "/", section: "top" },
    { label: "Conference", href: "/#conference", section: "conference" },
    { label: "Speakers", href: "/#speakers", section: "speakers" },
    { label: "Research", href: "/research", section: "research-page" },
    { label: "Registration", href: "/registration", section: "registration" },
  ],
  submitHref: "/submit",
  maxUploadMb: Number(process.env.MAX_UPLOAD_MB ?? 10),
};
